### ISSUE TITLE
Could not find package mpay24/mpay24-laravel at any version for your minimum-stability...

### ISSUE THREAD

**Issue by vedtam** [stefanpolzer/mpay24-laravel#1]
Hi,

I try to use your package but composer throws:

> Could not find package mpay24/mpay24-laravel at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 

Thanks!

**Comment by stefanpolzer** [comment]
Hi @vedtam,

The Read me is intent to work, if MPAY24 make this a official Repository.
At the moment you have to add this repository manual to your composer file:

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/stefanpolzer/mpay24-laravel"
    }
  ],
  "require": {
    "php": ">=7.0.0",
    "ext-intl": "*",
    "laravel/framework": "5.*",

    "mpay24/mpay24-laravel": "dev-master",
    "mpay24/mpay24-php": "~4.0",
  },
```

**Comment by vedtam** [comment]
Dear @stefanpolzer,

Thanks for the info, it did install nicely. However I have a small glitch when I try to create a new "order object": 

```
$mdxi = new ORDER();
$mdxi->Order->Tid = "123";
$mdxi->Order->Price = "1.00";
```
it throws:

> Class 'App\Http\Controllers\ORDER' not found

I guess for the order class to work I need to create another facade and ServiceProvider?

By the way, I would like to forward the user to a payment page generated by Mpay24, but their documentation is kinda confusing, your library is meant for handling payments on the merchant's werbsite, ritght?

Thanks!

**Comment by stefanpolzer** [comment]
I added the order class to the code so you can get all from one ServiceProvider. Now you can do:
```
$mdxi = app()->mpay24order;
$mdxi->Order->Tid = "123";
$mdxi->Order->Price = "1.00";
```
I hope that helps.

**Comment by vedtam** [comment]
Niceee! Thanks, its perfect.

**Comment by vedtam** [comment]
Sorry for bothering @stefanpolzer :P

While testing the Redirect integration using the credentials received from Mpay24, I get this error as response:

```
response: """
      <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n
      <html><head>\n
      <title>401 Unauthorized</title>\n
      </head><body>\n
      <h1>Unauthorized</h1>\n
      <p>This server could not verify that you\n
      are authorized to access the document\n
      requested.  Either you supplied the wrong\n
      credentials (e.g., bad password), or your\n
      browser doesn't understand how to supply\n
      the credentials required.</p>\n
      </body></html>\n
      """
```

I am wondering this may happen because I am testing on **localhost**?

Thanks!

**Comment by stefanpolzer** [comment]
This is comming from the  [mpay24](https://github.com/mpay24/mpay24-php) as a response to your request.
Please check you configuration. Is you merchant-id valid?

**Comment by vedtam** [comment]
I double checked the my credentials and are correct. Furthermore I have uploaded the site on a live server and tried testing there. Now the error is not present any more but the page won't forward to Mpay24 still, and I get a blank screen.

respose now is not helping too much:

![screen shot 2018-03-17 at 14 07 19](https://user-images.githubusercontent.com/4981592/37555227-df4e073e-29ec-11e8-831e-120ba8ea5995.png)

**Comment by stefanpolzer** [comment]
Redirection is not comming by itself. 
https://github.com/mpay24/mpay24-php/blob/master/examples/checkout.php

The Laravel version with this Fasade could look somethink like this:

```
$mpay24 = app()->mpay24;
$mdxi   = app()->mpay24order;

$mdxi->Order->Tid               = "123 TID";
$mdxi->Order->Price             = "1.00";
$mdxi->Order->URL->Success      = "http://yourdomain.com/success";
$mdxi->Order->URL->Error        = "http://yourdomain.com/error";
$mdxi->Order->URL->Confirmation = "http://yourdomain.com/confirmation";

$location = $mpay24->paymentPage($mdxi)->getLocation()

return redirect()->to($location);
```
If this don't work check the content of your `$location` response

**Comment by vedtam** [comment]
Oh, silly me, I used the example from the docs, but for redirecting I forgot to use the laravel helper method and instead I used:

`header('Location: '.$paymentPageURL);`

Thanks to your suggestion using redirect() its all fine now on the live server.

PS. on localhost it still fails to authenticate, but I gonna finish the integration on the live server.

Thanks!
Have a nice day

**Comment by stefanpolzer** [comment]
No problem ... I think about adding this to my own Docs, so People don't get confused

BTW: if you have a other problem, that is not relater to this topic:
#### [Could not find package mpay24/mpay24-laravel at any version for your minimum-stability](https://github.com/stefanpolzer/mpay24-laravel/issues/1)
Please open up a new issue, so other could benefit from it as well, thx
