### ISSUE TITLE
"Undefined variable: name" when setting 'BillingAddr' object

### ISSUE THREAD

**Issue by vedtam** [stefanpolzer/mpay24-laravel#2]
Hi,

I have set up the Order object while following the mPAY24 docs. Now as a last step I wanted to fill the `BillingAddr` object, but when I try to submit the order, before I get forwarded to the payment page, Laravel throws:

> ErrorException (E_NOTICE)
> Undefined variable: name

![error](https://user-images.githubusercontent.com/4981592/37558672-0bdde520-2a20-11e8-85de-fef914318508.jpg)

my pay function:

```
public function pay(Request $request) {
      $cart = Cart::content();
      $mpay24 = app()->mpay24;
      $mdxi   = app()->mpay24order;

      // dd($cart);

      $mdxi->Order->Tid                   = "1";
      $mdxi->Order->Price                 = Cart::total();

      $mdxi->Order->BillingAddr->setMode("ReadOnly");
      $mdxi->Order->BillingAddr->Name     = 'George';
      $mdxi->Order->BillingAddr->Email    = 'test@yahoo.co,';
      $mdxi->Order->BillingAddr->Phone    = '3334444555';
      $mdxi->Order->BillingAddr->Street   = 'Foo Street';
      $mdxi->Order->BillingAddr->Zip      = '999';
      $mdxi->Order->BillingAddr->City     = 'Foo City';
      $mdxi->Order->BillingAddr->Country  = 'Foo Country';

      $mdxi->Order->URL->Success      = 'http://mysite.com/success';
      $mdxi->Order->URL->Error        = 'http://mysite.com//error';
      $mdxi->Order->URL->Confirmation = 'http://mysite.com//confirmation';

      $paymentPageURL = $mpay24->paymentPage($mdxi)->getLocation(); // redirect location to the payment page
      return redirect()->to($paymentPageURL);
}
```

if I comment out the `BillingAddr` part, the payment gets forwarded to mPAY24, but obviously this is not what I want.

Btw when I open `Mpay24Order` at line 75, I can't see any refrence to $name.
What could be wrong?

**Comment by stefanpolzer** [comment]
Hi @vedtam this is clearly a Bug in the mpay24 Code. 

But try to use
`$mdxi->Order->BillingAddr->mode = 'ReadOnly';` instate.
I'm not sure if this works.

You may want to open a issue on https://github.com/mpay24/mpay24-php so somebody can write a PR

**Comment by vedtam** [comment]
I have tried, unfortunately it fails:

> The schema you have created is not valid!<br><br>Element 'BillingAddr': The attribute 'Mode' is required but missing.<br>Element 'mode': This element is not expected. Expected is one of ( Name, FirstName ).<br><textarea cols='100' rows='30'><?xml version="1.0" encoding="UTF-8"?> <Order> <Tid>1</Tid> <Price>88.00</Price> <BillingAddr> <mode>ReadOnly</mode> <Name>George</Name> <Email>test@yahoo.co,</Email> <Phone>3334444555</Phone> <Street>Foo Street</Street> <Zip>999</Zip> <City>Foo City</City> <Country>Foo Country</Country> </BillingAddr> <URL> 

I try open an issue on mpay24-php.
Thanks.

**Comment by stefanpolzer** [comment]
There is already a PR for this [#72 on mpay24](https://github.com/mpay24/mpay24-php/pull/72), but it is not in the master branch yet.
I hope they will to it soon!

**Comment by vedtam** [comment]
Thanks for the suggestion, what an obvious bug. Now it accepts the "Read Only" flag, but there is another issue. If I try to use any of the: Street, Zip, City, Country variables it throws:

`The schema you have created is not valid! Element 'Street': This element is not expected.`

![screen-shot-2018-03-18-at-10 19 56](https://user-images.githubusercontent.com/4981592/37564095-867b9e0e-2a97-11e8-8e47-8fa2ca1a74ae.jpg)


I am wondering, why this many bugs in mPAY24? :D

**Comment by vedtam** [comment]
Dear @stefanpolzer,

I ended up not submitting the clients details to overcome this bug, then I wanted to submit at least the `ShoppingCart` object, but I receive the same error as above:

`The schema you have created is not valid! Element 'ShoppingCart': This element is not expected. `

I am wondering, can my code be possibly wrong? Can you please take a look?

```
public function pay(Request $request) {

  $mpay24 = app()->mpay24;
  $mdxi   = app()->mpay24order;

  $mdxi->Order->Tid                     = "1";
  $mdxi->Order->Price                   = "20";
  
  $mdxi->Order->ShoppingCart->Item->Number = "Item Number 2";
  $mdxi->Order->ShoppingCart->Item->ProductNr = "Product Number 2";
  $mdxi->Order->ShoppingCart->Item->Description = "Description 2";
  $mdxi->Order->ShoppingCart->Item->Package = "Package 2";
  $mdxi->Order->ShoppingCart->Item->Quantity = 1;
  $mdxi->Order->ShoppingCart->Item->ItemPrice = 5.67;
  $mdxi->Order->ShoppingCart->Item->Price = 5.67;


  $mdxi->Order->URL->Success      = 'http://mysite.com/success';
  $mdxi->Order->URL->Error        = 'http://mysite.com/error';
  $mdxi->Order->URL->Confirmation = 'http://mysite.com/confirmation';

  $paymentPageURL = $mpay24->paymentPage($mdxi)->getLocation(); 
  return redirect()->to($paymentPageURL);
}
```

**Comment by vedtam** [comment]
I was told that the order I have passed the variables was wrong :\ 

After rearranging the object now its working.
